name: deploy on push
on: [push]
jobs:
  deploy-app:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code to build server
        uses: actions/checkout@v3
      - name: copy file to the server
        uses: appleboy/scp-action@master

        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USERNAME }}
          key: ${{ secrets.PROD_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "./html/*"
          target: "/var/www/html"
          strip_components: 1
